//
// Created by David Seery on 22/03/2017.
// --@@ // Copyright (c) 2017 University of Sussex. All rights reserved.
//
// This file is part of the Sussex Effective Field Theory for
// Large-Scale Structure platform (LSSEFT).
//
// LSSEFT is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
//
// LSSEFT is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with LSSEFT.  If not, see <http://www.gnu.org/licenses/>.
//
// @license: GPL-2
// @contributor: David Seery <D.Seery@sussex.ac.uk>
// --@@
//

#include "database/data_manager.h"


void data_manager::setup_write(transfer_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());

    sqlite3_operations::drop_index(this->handle, this->policy.transfer_table(), { "mid", "kid", "zid" });
  }


void data_manager::setup_growth_write()
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());
    
    sqlite3_operations::drop_index(this->handle, this->policy.D_factor_table(), { "mid", "params_id", "zid" });
    sqlite3_operations::drop_index(this->handle, this->policy.f_factor_table(), { "mid", "params_id", "zid" });
  }


void data_manager::setup_write(loop_integral_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());

#include "autogenerated/dropidx_kernel_stmts.cpp"
  }


void data_manager::setup_write(filter_Pk_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());

    sqlite3_operations::drop_index(this->handle, this->policy.Pk_linear_table(), "kid");
  }


void data_manager::setup_write(Matsubara_XY_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());
  }


void data_manager::setup_write(one_loop_Pk_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());

#include "autogenerated/dropidx_Pk_stmts.cpp"
  }


void data_manager::setup_write(multipole_Pk_work_list& work)
  {
    sqlite3_operations::write_performance_pragmas(this->handle, this->arg_cache.is_network_mode());
    
#include "autogenerated/dropidx_multipole_stmts.cpp"
  }


void data_manager::finalize_write(transfer_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);
    
    sqlite3_operations::create_index(this->handle, this->policy.transfer_table(), { "mid", "kid", "zid" });
    
    sqlite3_operations::analyze(this->handle);
  }


void data_manager::finalize_growth_write()
  {
    sqlite3_operations::default_pragmas(this->handle);
    
    sqlite3_operations::create_index(this->handle, this->policy.D_factor_table(), { "mid", "params_id", "zid" });
    sqlite3_operations::create_index(this->handle, this->policy.f_factor_table(), { "mid", "params_id", "zid" });
    
    sqlite3_operations::analyze(this->handle);
  }


void data_manager::finalize_write(loop_integral_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);

#include "autogenerated/makeidx_kernel_stmts.cpp"

    sqlite3_operations::analyze(this->handle);
  }


void data_manager::finalize_write(filter_Pk_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);

    sqlite3_operations::create_index(this->handle, this->policy.Pk_linear_table(), "kid");
  }


void data_manager::finalize_write(Matsubara_XY_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);
  }


void data_manager::finalize_write(one_loop_Pk_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);
    
#include "autogenerated/makeidx_Pk_stmts.cpp"

    sqlite3_operations::analyze(this->handle);
  }


void data_manager::finalize_write(multipole_Pk_work_list& work)
  {
    sqlite3_operations::default_pragmas(this->handle);

#include "autogenerated/makeidx_multipole_stmts.cpp"

    sqlite3_operations::analyze(this->handle);
  }
